# automatically generated by the FlatBuffers compiler, do not modify
# Generated from inference_request.fbs

# namespace: forge

import typing as t
from flatbuffers import compat
from flatbuffers import util
from flatbuffers import builder
from flatbuffers import encoder
from flatbuffers.flexbuffers import Load
import flatbuffers


class InferenceRequest(object):
    __slots__ = ('_tab')

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InferenceRequest()
        x._tab = flatbuffers.table.Table(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInferenceRequest(cls, buf, offset=0):
        return cls.GetRootAs(buf, offset)

    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    def _buf(self, i: int = 0) -> bytes:
        return self._tab.Bytes

    def _tab(self, i: int = 0):
        return self._tab

    @property
    def Prompt(self) -> str:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    @property
    def Width(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1024

    @property
    def Height(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1024

    @property
    def NumSteps(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 4

    @property
    def GuidanceScale(self) -> float:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.5

    @property
    def Seed(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    @property
    def OutputFormat(self) -> str:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return "png"


class InferenceRequestT(object):

    # InferenceRequestT
    def __init__(self):
        self.prompt = ""  # str
        self.width = 1024  # int
        self.height = 1024  # int
        self.numSteps = 4  # int
        self.guidanceScale = 0.5  # float
        self.seed = 0  # int
        self.outputFormat = "png"  # str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        inferenceRequest = InferenceRequest()
        inferenceRequest.Init(buf, pos)
        return cls.InitFromObj(inferenceRequest)

    @classmethod
    def InitFromObj(cls, inferenceRequest):
        x = InferenceRequestT()
        x._UnPack(inferenceRequest)
        return x

    # InferenceRequestT
    def _UnPack(self, inferenceRequest):
        if inferenceRequest is None:
            return
        self.prompt = inferenceRequest.Prompt
        self.width = inferenceRequest.Width
        self.height = inferenceRequest.Height
        self.numSteps = inferenceRequest.NumSteps
        self.guidanceScale = inferenceRequest.GuidanceScale
        self.seed = inferenceRequest.Seed
        self.outputFormat = inferenceRequest.OutputFormat

    # InferenceRequestT
    def Pack(self, builder):
        InferenceRequestStart(builder)
        InferenceRequestAddPrompt(builder, self.prompt)
        InferenceRequestAddWidth(builder, self.width)
        InferenceRequestAddHeight(builder, self.height)
        InferenceRequestAddNumSteps(builder, self.numSteps)
        InferenceRequestAddGuidanceScale(builder, self.guidanceScale)
        InferenceRequestAddSeed(builder, self.seed)
        InferenceRequestAddOutputFormat(builder, self.outputFormat)
        inferenceRequest = InferenceRequestEnd(builder)
        return inferenceRequest


def CreateInferenceRequest(builder, prompt=None, width=None, height=None, numSteps=None, guidanceScale=None, seed=None, outputFormat=None):
    builder.StartObject(7)
    builder.PrependInt32Slot(5, seed, 0)
    builder.PrependInt32Slot(3, numSteps, 4)
    builder.PrependInt32Slot(1, width, 1024)
    builder.PrependInt32Slot(2, height, 1024)
    builder.PrependFloat64Slot(4, guidanceScale, 0.5)
    builder.PrependUOffsetTRelativeSlot(6, outputFormat, 0)
    builder.PrependUOffsetTRelativeSlot(0, prompt, 0)
    return builder.EndObject()


def InferenceRequestStart(builder):
    builder.StartObject(7)


def InferenceRequestAddPrompt(builder, prompt):
    builder.PrependUOffsetTRelativeSlot(0, prompt, 0)


def InferenceRequestAddWidth(builder, width):
    builder.PrependInt32Slot(1, width, 1024)


def InferenceRequestAddHeight(builder, height):
    builder.PrependInt32Slot(2, height, 1024)


def InferenceRequestAddNumSteps(builder, numSteps):
    builder.PrependInt32Slot(3, numSteps, 4)


def InferenceRequestAddGuidanceScale(builder, guidanceScale):
    builder.PrependFloat64Slot(4, guidanceScale, 0.5)


def InferenceRequestAddSeed(builder, seed):
    builder.PrependInt32Slot(5, seed, 0)


def InferenceRequestAddOutputFormat(builder, outputFormat):
    builder.PrependUOffsetTRelativeSlot(6, outputFormat, 0)


def InferenceRequestEnd(builder):
    return builder.EndObject()


def InferenceRequestStartPromptVector(builder, numElems=0):
    return builder.StartVector(4, numElems, 4)


def InferenceRequestEndPromptVector(builder):
    return builder.EndVector()


def InferenceRequestStartOutputFormatVector(builder, numElems=0):
    return builder.StartVector(4, numElems, 4)


def InferenceRequestEndOutputFormatVector(builder):
    return builder.EndVector()
